name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Create Pull Request with Standard Message
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b pr/deployment
          echo "## Description" > pr-message.md
          echo "" >> pr-message.md
          echo "Briefly describe the changes made in this PR and why they are necessary." >> pr-message.md
          echo "" >> pr-message.md
          echo "## Type of Change" >> pr-message.md
          echo "" >> pr-message.md
          echo "- [ ] Bug fix" >> pr-message.md
          echo "- [ ] New feature" >> pr-message.md
          echo "- [ ] Breaking change" >> pr-message.md
          echo "- [ ] Documentation update" >> pr-message.md
          echo "" >> pr-message.md
          echo "## How Has This Been Tested?" >> pr-message.md
          echo "" >> pr-message.md
          echo "Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce." >> pr-message.md
          echo "" >> pr-message.md
          echo "## Screenshots (if applicable)" >> pr-message.md
          echo "" >> pr-message.md
          echo "If your changes include UI updates, please add screenshots to demonstrate them." >> pr-message.md
          echo "" >> pr-message.md
          echo "## Checklist" >> pr-message.md
          echo "" >> pr-message.md
          echo "- [ ] My code follows the style guidelines of this project" >> pr-message.md
          echo "- [ ] I have performed a self-review of my code" >> pr-message.md
          echo "- [ ] I have commented my code, particularly in hard-to-understand areas" >> pr-message.md
          echo "- [ ] My changes generate no new warnings" >> pr-message.md
          echo "- [ ] I have added tests to verify my changes" >> pr-message.md
          echo "- [ ] New and existing tests pass with my changes" >> pr-message.md
          git add pr-message.md
          git commit -m "Add standard PR message for production deployment"
          git push origin pr/deployment
          gh pr create --title "Production Deployment" --body "$(cat pr-message.md)" --base main --head pr/deployment
